sudo: false
language: python
env:
- TOXENV=py25
- TOXENV=py26
- TOXENV=py27
- TOXENV=py30
- TOXENV=py31
- TOXENV=py32
- TOXENV=py33
- TOXENV=py34
- TOXENV=pypy
- TOXENV=pypy3
install:
- pip install tox
- pip install python-coveralls
- pip install codecov
script:
- tox
after_success:
- codecov
deploy:
  provider: pypi
  user: sbuss
  password:
    secure: O6mfmB8NaEkZt1q2zMjgFhJg768WMsg0qREwZ4eRZ6IFrKtEdAUQyilt7N8SgHoleZhpvLc2n3B+4/MgRKBuPxcNdUtr14UsKOO0lu0/4GVNquMuc5UjQHFoy+oXajhYnmJrdIhRGob2zjqN/tP56imVOdsX3UOSs2CInxlhi2A=
  on:
    tags: true
    repo: sbuss/bitmerchant
    branch: master
